# Generated by Django 4.1.5 on 2023-02-07 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_promocoes_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocoes",
            name="data_publicacao",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 2, 7, 21, 58, 5, 761745, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
