# Generated by Django 4.1.5 on 2023-02-08 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_promocoes_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocoes",
            name="data_publicacao",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
