# Generated by Django 4.1.5 on 2023-02-09 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_promocoes_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocoes",
            name="data_publicacao",
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
